### ISSUE TITLE
Matched words remain displayed on Advanced Mode domain

### ISSUE THREAD

**Issue by scottmeup** [richardfrost/AdvancedProfanityFilter#131]
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

## Description
Count of successfully matched words from browser addon icon properly displayed for Advanced Mode site, but matched words are still displayed in full on the web page.

### Details (Bugs Only)

Chrome Version: 73.0.3683.86
Extension Version: 2.1.0
Operating System: OSX 10.10.5
Site(s) Affected: https://www.reddit.com/user/*

### Steps to reproduce (Bugs only)

1. Add word/phrase `(•\s\d+\s)(point)(s?)(\s•)`, type: regex.
2. Add advanced domain `www.reddit.com` 
3. In browser, go to `https://www.reddit.com/user/spez` or any other user page

## Other details

No matches for the above regex are recorded unless site is enabled as Advanced Mode

### Screenshots

https://i.imgur.com/BPgWB8H.jpg

Screenshot of affected site, count of matches and highlighted red box around 3 examples of match.

**Comment by richardfrost** [comment]
Thanks for reporting the issue. I am not seeing exactly the same page as you, on mine it doesn't include the first `·` (I've tried both being logged in and not, so I don't think its related that):

![image](https://user-images.githubusercontent.com/1507205/55852697-42888a80-5b1b-11e9-8810-bd998e3fc20c.png)

The filter usually only looks at one element as a time , but you are trying to match across elements which is why it requires "Advanced mode":

![image](https://user-images.githubusercontent.com/1507205/55852631-07865700-5b1b-11e9-94ab-be9e6cc77338.png)



For me, both of these seem to work:
`(\d+\s)(points?)(\s+·)`
`\d+\spoints?\s+·`

![image](https://user-images.githubusercontent.com/1507205/55853133-0524fc80-5b1d-11e9-8167-d255f5c49196.png)

For ones that have lots of points (the last one in that screenshot has 2.1k) , you would probably need to adjust it to something like:

`[\d.]+k?\spoints?\s+·`.

Do you know why it might look different? Are you possibly using another extension or userscript that modifies Reddit?

**Comment by scottmeup** [comment]
Hi Richard, thanks for the quick reply.
I was using a few extensions that would have modified reddit (Adblock Plus, Privacy Badger, Reddit Enhancement Suite).
I've disabled all extensions apart from Advanced Profanity Filter and the behaviour remains the same,  it's very strange. I've attached a screenshot https://i.imgur.com/0RFBEtw.jpg .
Is there any other information that might be helpful or anything you would like me to try?

Kind regards - Andrew.

**Comment by richardfrost** [comment]
Well, at least one of my replies was quick! Anyway, I am not sure why our pages are different, but it does make it hard for me to test.

Could you adjust your regex to something like: `•\s+[\d.]+k?\spoints?\s+•`?

**Comment by richardfrost** [comment]
Okay - I found out what is different. You are using the old Reddit interface. I can also explain what is happening. If you use this: `[\d.]+k?\spoints?`, it should work, but will leave 2 `•` around it.

If you switch to the new redesign this should work to remove it: `[\d.]+k?\spoints?\s+·`.  Adjust as desired (like if you don't want to remove when there are over 1k points, etc).

Here is what is happening: the page gets rendered completely and filtered. Then, there is a process from Reddit that goes back and overwrites those changes back to the original. This is a pretty common practice, for instance when you want to hurry and get a page up, and then go back through and update content with the most recent values (number of points, for instance). Regardless of the reasoning, it is not something that the extension can control when it happens. This is also not a problem, **unless** you are trying to match across elements, and only 1 element gets modified. The extension is watching for changes, but since the only change is `11 points`, and not the surrounding `•`, the regex doesn't match, and therefore isn't filtered.

I don't think there is really anything else to do on this, but hopefully one of those workarounds will help with the situation. Let me know if you have any other questions or concerns.

**Comment by richardfrost** [comment]
I'm going to close this for now, but if you have any more questions feel free to reply here.
