### ISSUE TITLE
Bright green background for profanity count

### ISSUE THREAD

**Issue by JayH2971** [richardfrost/AdvancedProfanityFilter#148]
This isn't a bug, but it also isn't a feature and I didn't know where to better put it. Up until now APF's used a moderate blue background for its counter, but the newest version changed it to bright green on Youtube. The text is white and that makes it hard to read on a high resolution: https://i.imgur.com/XLyKXph.png

Imgur resized it but on my computer the icon is about 35 pixels high and very hard to read.

**Comment by richardfrost** [comment]
The change was by design, but I agree that the color isn't great.

Would orange be better?

![image](https://user-images.githubusercontent.com/1507205/59241118-a3881980-8bc3-11e9-89e0-6d87cc5834a0.png)

Or maybe a purple?

![image](https://user-images.githubusercontent.com/1507205/59241222-0d082800-8bc4-11e9-86ed-bcac16532923.png)

I'm open to suggestions! 😄 

The reason for the color change is just to notify the user that audio muting is enabled for the current site.

**Comment by JayH2971** [comment]
It's a good idea. My suggestion would be purple or blue for normal and dark green for audio capability, depending on how clearly it comes through.

**Comment by richardfrost** [comment]
Thanks for the input!

How is this green?

![image](https://user-images.githubusercontent.com/1507205/59244103-4a72b280-8bd0-11e9-9b0a-de6b9fb8e678.png)

**Comment by JayH2971** [comment]
Much better!

**Comment by richardfrost** [comment]
Cool! I have released [2.1.6](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.6) with the change. Feel free to share any comments or other suggestions you may have!
