### ISSUE TITLE
Audio filtering: filtered count carries over between videos in YouTube playlist

### ISSUE THREAD

**Issue by JayH2971** [richardfrost/AdvancedProfanityFilter#150]
#### :bug: Description
The profanity count will accumulate from past videos, even when the YouTube video changes to another.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to a YT video in a playlist **(https://youtu.be/aJGBcZyxb_Q?list=UUCF6pCTGMKdo9r_kFQS-H3Q&t=116)**
2. Allow a censored word to appear in audio filtering (in this case, "ass")
3. Press Shift-N to advance to next video
4. APF's extension icon should carry over the filtered words from the first video into the second, and so on.

#### :heavy_check_mark: Expected behavior
The profanity count should revert to zero at the start of a new video, as is done with all other pages.

#### :computer: Details
 - **OS:** Linux Mint 19.1
 - **Browser:** Chrome
 - **Browser Version:** 75.0.3770.90
 - **Affected site(s):** www.youtube.com

**Comment by richardfrost** [comment]
Thanks for taking the time to report this.

Currently this is by design, as the filter is working on a per-page basis. It keeps state on a page unless there is a full page navigation/reload. So, if you reload the page it should reset the counter. The counter also tracks words found in the rest of the page too. Another way to say this, is that the counter is simply keeping track of how many words have been filtered. Back when the counter/summary was implemented users reported that they liked having a "running total" of filtered words, so I'm hesitant to change the behavior without good reason.

Is there a specific use case you see for this? I'll think about it more as well.

**Comment by JayH2971** [comment]
Ah, I didn't realize it was intentional. I thought the purpose was to show it for each page. No big deal, that's fine.

**Comment by richardfrost** [comment]
No worries! Thanks for pointing it out. If its confusing to someone, I'm sure others have had the same question. I'll still think about it more and see if I can find a way to improve it.

**Comment by duckbrain** [comment]
It might be more intuitive to reset the count when the location changes in a SPA, because to a user, that is supposed to appear as a new page. Based on appearances, this is what YouTube is doing.

You could replace the `history.pushState` and `history.replaceState` functions with an implementation that resets the counter to catch when sites change the state themselves, then use the [popstate event](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) to catch when the user changes the state.

I don't really see the current implementation as a problem; just an idea for handling it.
