### ISSUE TITLE
Not censoring words with - in them.  Also not working at all on Bing suggestions.

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#181]
I got quite upset doing a Google search and the f word was shown but not censored because it had - in it.  Example "d-o-g" won't censor.  I don't feel like adding the word to the list manually I hate even typing it out but then I would have to add the other swears too.  I also have matching repeated characters on.

I also found out that Bing suggestions are not filtering any words at all.
![2020-01-01_160924](https://user-images.githubusercontent.com/39742654/71646153-3ba93580-2cb1-11ea-85da-8ce49af9da1d.png)

Also attached is my filter list.
[apf-backup-2020-01-02.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/4014541/apf-backup-2020-01-02.zip)

**Comment by richardfrost** [comment]
I'm sorry about those unfortunate experiences.

1. I'll look at adding a few more characters (optionally) between words. I'm thinking for now it would be: `-` and `_`. That should allow you to filter words with any combination with those characters. Example: If you wanted to filter `dog`, then `d-o-----g` would still be filtered, as well as `d_o_g`. Seems like a pretty nice way to filter more without much effort on the user's part. I would probably set it as the default as well.

2. As for Bing, the reason it doesn't filter is that the word is spread across multiple HTML Elements. They do it because they apply a different style to the "guessed completion" as you type. Try searching for "frankly my dear" (if you are filtering `da**`) it should work. But as you type the rest of the phrase and get to the "d" it will become visible again. That's because the filter now sees `d` and `a..`, which isn't in the list of words to filter. To fix this issue, turn on Advanced Mode on bing.com and the problem should be fixed. I'll consider adding Bing as a default advanced domain.

Let me know if you have any other ideas, or comments on these suggestions. Thanks again for your helpful input.

**Comment by tonyram57** [comment]
Also it's not working if someone puts a space example "d og" is not censored.

**Comment by richardfrost** [comment]
I submitted version 2.6.0 today. When you get the update, can you try setting the words you'd like to match separators in the options and see how it works for you?

**Comment by tonyram57** [comment]
I enabled the option it is filtering the words with separators now.  Thanks.

**Comment by tonyram57** [comment]
It is filtering words with separators.  However if I reset my settings which resets the swear words list it stops filtering the words with separators.  I had to restore my backup from the 14th to get it working again.

**Comment by richardfrost** [comment]
That's not good. I'll take a look!

**Comment by richardfrost** [comment]
When you say "reset my settings", does that mean restore defaults? Because by default, only a few of the words are setup to match with separators. The setting has to be turned on for every word you want to have separators matched in. So, if you wanted it on all words for example, you have to set it for each word in the list.

If there is something else that's wrong, I'm happy to take a look at it.

**Comment by richardfrost** [comment]
Gonna close this due to inactivity, but feel free to comment if there is still something to do here.
