### ISSUE TITLE
Filtering even when subtitles are disabled on Disney+ still

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#182]
I was watching Muppet Treasure Island on Disney+ with subtitles turned off, and it censored the word "hell". It's doing it again.

**Comment by richardfrost** [comment]
I'm sorry that this bug came back. I'll take a look at it as soon an I can.

**Comment by richardfrost** [comment]
Sorry It has taken me so long to get to this. So I just tried to reproduce this and wasn't able to, at least not unexpectedly. Here is the expected usage:


1. Start playing the video
2. If the subtitles are on (remembered from a previous session) or turned on manually, simply turning them off won't disable the filter. A reload of the page with the subtitles turned off will need to take place to disable the filter.

The way the filter works on Disney+, is if the captions/subtitles are enabled, they will all be processed by the filter. So, if you disable the subtitles while the video is already playing, the filter will likely have already processed them all.

If it proves too much to keep track of, the simpler alternative is to toggle the filter off for [disneyplus.com](disneyplus.com). It can always easily be turned back on if desired from the [extension popup window](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#popup). To toggle the filter for the current page, just click on the extension button and then click on the switch at the top (blue is "on", grey is "off").

If you have other steps you'd like to me try, just let me know. Otherwise, if this proves enough I'll go ahead and close this.

**Comment by richardfrost** [comment]
Going to close this, but feel free to open it again if the issue persists.
