### ISSUE TITLE
Crunchyroll.com addition?

### ISSUE THREAD

**Issue by crider354** [richardfrost/AdvancedProfanityFilter#205]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: The Site
Crunchyroll.com

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<div class="subtitle-container">
  <p class="subtitle-text">Subtitle text</p>
</div>
```

#### :pencil: Additional notes
I don't know code but I was hoping you could help me figure out how to get the english subtitles to filter. Thank you!

**Comment by richardfrost** [comment]
I took a few minutes to see how they do their subtitles, and its actually very similar to the way that [vrv.co](vrv.co) does theirs. Its been requested a few times, but will be quite an undertaking. I haven't had the time to devote to it, but maybe I'll be able to attempt it in the future.

Basically, when playing the video, a request for the subtitle data is made, and then it converts those subtitles to an HTML canvas (essentially an image). Because of that, it isn't possible for the filter to work as it normally does (by scanning text). To make it work, the filter will probably need to make a duplicate request for the subtitle information, and filter with that.

This will probably have to be put on the back burner for a while, but hopefully I'll find some time to try and tackle it.

**Comment by crider354** [comment]
Thank you for your efforts and product!

**Comment by richardfrost** [comment]
I'm excited to announce some experimental support for filtering/muting on crunchyroll.com! To use it, you'll need to be on version [2.11.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.11.0)+. If you get a chance to try it out, I'd love to hear feedback on your experience. If you come across a video that doesn't work, please let me know here and I will try to investigate it. If you have a good experience, please let me know too!

For this to work, you'll need to enable the "Audio muting" feature (Options > Audio Tab: "Mute audio on supported video sites").

# Tips and Tricks:
These are pretty technical, so if you think you need help with one, let me know and I can help you for your particular situation.

### Muting
Because this ties into the audio filter function, whenever a filtered word is present the audio will be muted. If you just want the text to be filtered, follow these steps:
1. Copy the config for the desired site: (Options > Audio: "View Supported Sites") and copy it into the Custom Audio Sites box (you'll need to close the "Supported Audio Sites" window first)
2. Add the following line right after `"mode": "cue"`: `"muteMethod": 2`
3. Click the save button, and then reload the desired page for the changes to take effect

##### Example:
```json
{
  "www.crunchyroll.com": [
    {
      "displaySelector": "canvas#velocity-canvas",
      "externalSub": true,
      "externalSubVar": "window.v1config.media.subtitles",
      "iframe": true,
      "mode": "cue",
      "muteMethod": 2,
      "showSubtitles": 0,
      "videoCueLanguage": "enUS",
      "videoCueRequireShowing": false
    }
  ]
}
```

### Language
Currently all the testing I did was around the English language for the captions/subtitles. If you want a different language, you'll need to follow a simliar process as the Muting section above, but instead of `"muteMethod": 2`, you'll use `"videoCueLanguage": "en-US"` (replacing "en-US" with an appropriate language name).

**Comment by crider354** [comment]
Wow! Thank you for all of your hard work!
    On Monday, October 19, 2020, 08:45:17 AM PDT, Richard Frost <notifications@github.com> wrote:  
 
 


I'm excited to announce some experimental support for filtering/muting on crunchyroll.com! To use it, you'll need to be on version 2.11.0+. If you get a chance to try it out, I'd love to hear feedback on your experience. If you come across a video that doesn't work, please let me know here and I will try to investigate it. If you have a good experience, please let me know too!

For this to work, you'll need to enable the "Audio muting" feature (Options > Audio Tab: "Mute audio on supported video sites").

Tips and Tricks:

These are pretty technical, so if you think you need help with one, let me know and I can help you for your particular situation.

Muting

Because this ties into the audio filter function, whenever a filtered word is present the audio will be muted. If you just want the text to be filtered, follow these steps:
   
   - Copy the config for the desired site: (Options > Audio: "View Supported Sites") and copy it into the Custom Audio Sites box (you'll need to close the "Supported Audio Sites" window first)
   - Add the following line right after "mode": "cue": "muteMethod": 2
   - Click the save button, and then reload the desired page for the changes to take effect

Example:
{
  "www.crunchyroll.com": [
    {
      "displaySelector": "canvas#velocity-canvas",
      "externalSub": true,
      "externalSubVar": "window.v1config.media.subtitles",
      "iframe": true,
      "mode": "cue",
      "muteMethod": 2,
      "showSubtitles": 0,
      "videoCueLanguage": "enUS",
      "videoCueRequireShowing": false
    }
  ]
}
Language

Currently all the testing I did was around the English language for the captions/subtitles. If you want a different language, you'll need to follow a simliar process as the Muting section above, but instead of "muteMethod": 2, you'll use "videoCueLanguage": "en-US" (replacing "en-US" with an appropriate language name).

**Comment by richardfrost** [comment]
I'm going to go ahead and close this since I haven't heard anything back yet. As always, feel free to comment here, or re-open if you run into trouble.
