### ISSUE TITLE
Custom Audio Site (GetChannels.com) 

### ISSUE THREAD

**Issue by asztalgj** [richardfrost/AdvancedProfanityFilter#215]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: The Site
http://dvr-ds.local:8089/admin/recordings/movies

#### :speech_balloon: Subtitle Element/Node
<div style="position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px; margin: 1.5%;"><div style="text-align: center; font: 21.61px sans-serif; white-space: pre-line; position: absolute; direction: ltr; writing-mode: horizontal-tb; left: 210.484px; width: 420.984px; top: 407.219px; bottom: 0px; right: 210.5px; height: 25px; background-color: rgba(0, 0, 0, 0);"><div style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); position: relative; left: 0px; right: 0px; top: 0px; bottom: 0px; display: inline; writing-mode: horizontal-tb; unicode-bidi: plaintext; font-family: sans-serif;">HEY, HOW YOU DOING, MAN?</div></div></div>

#### :pencil: Additional notes
I'm running GetChannels.com on my local Synology NAS.  I could not find a class.  What can I do next?  Thanks!

**Comment by richardfrost** [comment]
Hi There! Thanks for reaching out. Unfortunately I don't think that I have enough to go on to help out with this yet. From a quick bit of research, it looks like this is a DVR server that is running on your NAS. Is that right? Since I don't have access to it, I probably can't give a lot of specific help. Have you had a chance to look at the [Custom Audio Muting Site](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site) page? It might have some helpful information in there, though it is quite technical. If its not enough help, I'd be happy to arrange something where we could do a screen share or something similar.

**Comment by richardfrost** [comment]
I'm going to close this for now, but if anyone is interested in helping me out with this, I'm happy to see what it would take to add support for it. Feel free to comment here and I'll take a look.
