### ISSUE TITLE
APF For Android YouTube or YouTube Vanced

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#220]
Hello! Now I'm not even sure if this is even possible, but if it did exist, it would be amazing. While the bookmarklet does work really well, I find UI is a little better in the app than in Chrome. However, as you can't run scripts in it, it won't mute it or filter any text in it. But, if there was a way to combine this extension with the app, it would make my mobile YouTube experience ten times better. However, his sounds like more of a new project then something you could just add to this project, which is why I don't think it belongs here.

**Comment by richardfrost** [comment]
Thanks for the idea. Unfortunately I fear you are correct though. From what I can tell, both YouTube and YouTube Vanced are both closed source Java-based apps. Since they are closed source, it would require the project to have a desire to include it. Since they are Java, it would require a rewrite of the filter since it is written in Javascript (even though they both start with "java", they are not related/comparable). I think I'll close this, but if something changes in the future we can re-open it or make a new one.

Another option on Android might be to use a browser that supports extensions/add-ons (Kiwi, Firefox for example). That won't really help with the YouTube interface, but it is easier to manage and use than the bookmarklet.
