### ISSUE TITLE
Not working on newest Firefox for android

### ISSUE THREAD

**Issue by Imveryweird** [richardfrost/AdvancedProfanityFilter#243]
I'm not sure if there is anything you can do about this but this is a big issue as your addon is my most used one.

**Comment by richardfrost** [comment]
Thanks for reporting the issue. Do you have any more specifics as to what isn't working? I haven't noticed any issues with the latest version (`2.8.2`) on Firefox for Android `68.11.0`.

If you can get into the filter's options, maybe try exporting your current config as a backup, and then try restoring the defaults and seeing if that helps (Option page > Config tab).

**Comment by richardfrost** [comment]
I just got updated to Firefox `79.0.5`, and I think I see what you mean. The [newest version of Firefox for Android](https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android) is currently only allowing their curated list of [recommended extensions](https://support.mozilla.org/en-US/kb/recommended-extensions-program) to be installed.

Unfortunately APF is not on the list. According to this page, it is possible to [suggest an extension to be reviewed](https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_may-i-suggest-extensions-to-become-recommended) for possibly being included, so you may want to follow the instructions there. Since its my extension, I am not eligible to suggest it. I imagine that having suggestions from multiple people would help, so if anyone would like to see it, feel free to make it known.

In the meantime, if you are looking to run APF on Android, you may want to take a look at [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser), which is a chromium based browser that offers extension support.

**Comment by tonyram57** [comment]
You can also use Yandex browser which supports extensions.

I am keeping Firefox installed but I removed it from my home screen and refuse to use it until there is support for this extension as I don't trust any website not containing profanities.

**Comment by Imveryweird** [comment]
I use fennec fdroid to combat this. Yandex may be a solution.

**Comment by richardfrost** [comment]
Thanks for all the suggestions on ways to work around this issue. I hope that one day they open things up again so its not so hard to get on their curated list.

**Comment by richardfrost** [comment]
I just noticed that you can also add extensions using [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) by following the instructions [here](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/).

**Comment by richardfrost** [comment]
As of Firefox 120, APF is again officially supported directly on Firefox Mobile.

Reference: #522
