### ISSUE TITLE
Censoring for epub files 

### ISSUE THREAD

**Issue by Imveryweird** [richardfrost/AdvancedProfanityFilter#244]
I like my books swear word free. And I think this would help a lot. Thanks in advance.

**Comment by richardfrost** [comment]
Thanks for the suggestion! I agree that this would be a useful application as well, but unfortunately I think its a bit out of the realm for the browser extension due to the dependencies it would require.

I have another project ([Advanced Profanity Filter Web](https://github.com/richardfrost/AdvancedProfanityFilterWeb)) that uses the same APF library, so it is compatible with the same configuration. Its more of a back-burner project, and is probably barely alpha quality right now, but I have had success with filtering `.epub` and `.docx` files using it.

See the project's README for instructions to host it locally for yourself, or if you'd rather, you can test it on [heroku](https://advanced-profanity-filter.herokuapp.com/). (_Note: Its just a free instance on Heroku, so it may be slow, and subject to being shutdown if it sees too much use)_.

**Comment by Imveryweird** [comment]
The instance on heroku didn't work at all.

**Comment by richardfrost** [comment]
Did the page load at all? Was there an error message? How large is the epub that you are looking to filter?

**Comment by Imveryweird** [comment]
The page loaded, the epub is about 2mb and the only thing that wouldnt work was the filter page.

**Comment by richardfrost** [comment]
Would you mind sharing the file with me richard @ richardfrost.info?

What browser are you using? I've only tested with Chrome and Brave. I'll
test with Firefox later today. Are you using your own config file? If so,
does it work without providing one?

**Comment by Imveryweird** [comment]
The page loaded, the epub is about 2mb and the only thing that wouldnt work was the filter page.

**Comment by richardfrost** [comment]
Would you mind sharing the file with me richard @ richardfrost.info?


What browser are you using? I've only tested with Chrome and Brave. I'll
test with Firefox later today. Are you using your own config file? If so,
does it work without providing one?

**Comment by richardfrost** [comment]
I've just tested it with a handful of other epubs that I have, and from what I can tell its working.

Do you see an error message when you try to filter it, or does it just appear to do nothing?

**Comment by Imveryweird** [comment]
It just appears to do absolutely nothing.

**Comment by richardfrost** [comment]
Okay, I added some more logging (so hopefully I'll be able to track down errors better), and made an adjustment in how `.epub` files are handled. It was working on all the ebooks that I personally wanted to filter, but it seems that I was missing support for another valid epub format. I'm not sure it will fix it for the ones you've been trying, but give it a try.

For reference, here is a public domain ebook that was failing before, but should work with the new update:

[Chandler, Raymond - The Long Goodbye](https://www.fadedpage.com/showbook.php?pid=20140522)

**Comment by richardfrost** [comment]
@Imveryweird Just wanted to check in and see if you were able to try it after the changes I noted in the last comment?

**Comment by Imveryweird** [comment]
Yeah. The heroku instance has been working, read about 2 books on that. I forgot to tell you.

**Comment by richardfrost** [comment]
Awesome! 😄 Thanks for the update! I'll go ahead and close this for now. Feel free to open it again, or a new issue if you need.
