### ISSUE TITLE
Muting Emojis

### ISSUE THREAD

**Issue by vadoler** [richardfrost/AdvancedProfanityFilter#260]
Would you include Emojis in this extension?

**Comment by richardfrost** [comment]
I haven't come across a use case personally that needed this, but I just went to https://getemoji.com/ and selected an emoji, then using the context (right-click) menu, added it to the filter (Advanced Profanity Filter > Add selection to filter), refreshed the page and it filtered that emoji.

Do you have a specific instance where the filter isn't working?

**Comment by vadoler** [comment]
> I haven't come across a use case personally that needed this, but I just went to https://getemoji.com/ and selected an emoji, then using the context (right-click) menu, added it to the filter (Advanced Profanity Filter > Add selection to filter), refreshed the page and it filtered that emoji.
> 
> Do you have a specific instance where the filter isn't working? Or is there another use case that I'm not testing/thinking of with that test?

Thank you for the reply, It works fine in sites such as YouTube, But it doesn't on twitter, I think twitter use it's own emoji system, could you find a way to make it work on Twitter?

**Comment by vadoler** [comment]
> I haven't come across a use case personally that needed this, but I just went to https://getemoji.com/ and selected an emoji, then using the context (right-click) menu, added it to the filter (Advanced Profanity Filter > Add selection to filter), refreshed the page and it filtered that emoji.
> 
> Do you have a specific instance where the filter isn't working? Or is there another use case that I'm not testing/thinking of with that test?

Thank you for the reply, It works fine in sites such as YouTube, But it doesn't on twitter, I think twitter use it's own emoji system, could you find a way to make it work?

**Comment by richardfrost** [comment]
Yep, you are correct, twitter doesn't use typical emojis. They are actually images, which unfortunately aren't easy to filter.

![image](https://user-images.githubusercontent.com/1507205/97608914-95b17f00-19d8-11eb-8a32-708f376ef725.png)

Here is an example that uses the actual emoji for the `aria-label` and `img alt`:
```html
<div aria-label="☕" class="css-1dbjc4n r-xoduu5 r-1mlwlqe r-1d2f490 r-1udh08x r-u8s1d r-h9hxbl r-417010" style="height: 1.2em;">
  <div class="css-1dbjc4n r-1niwhzg r-vvn4in r-u6sd8q r-x3cy2q r-1p0dtai r-xoduu5 r-1pi2tsx r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-13qz1uu r-1wyyakw" style="background-image: url(&quot;https://abs-0.twimg.com/emoji/v2/svg/2615.svg&quot;);"></div>
  <img alt="☕" draggable="false" src="https://abs-0.twimg.com/emoji/v2/svg/2615.svg" class="css-9pa8cd">
</div>
```

And here is one that just uses a name ("us") for the `aria-label` and `img alt`:
```html
<div aria-label="🇺🇸" class="css-1dbjc4n r-xoduu5 r-1mlwlqe r-1d2f490 r-1udh08x r-u8s1d r-h9hxbl r-417010" style="height: 1.2em;">
  <div class="css-1dbjc4n r-1niwhzg r-vvn4in r-u6sd8q r-x3cy2q r-1p0dtai r-xoduu5 r-1pi2tsx r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-13qz1uu r-1wyyakw" style="background-image: url(&quot;https://abs-0.twimg.com/emoji/v2/svg/1f1fa-1f1f8.svg&quot;);"></div>
  <img alt="🇺🇸" draggable="false" src="https://abs-0.twimg.com/emoji/v2/svg/1f1fa-1f1f8.svg" class="css-9pa8cd">
</div>
```

Unfortunately this project isn't built to handle this situation very well. You might try an adblocker where you could block specific requests for images. If an image fails to load, the page should then fall back to the `img alt`, which the filter could then handle. Let me know if you have any other questions, but I think I'll close this because it just doesn't seem like a very good fit here.

**Comment by vadoler** [comment]
The AdBlock trick did it well! Thanks for the help.

**Comment by richardfrost** [comment]
Awesome! I'm glad it worked for you.
