### ISSUE TITLE
Your heroku webpage is not working anymore

### ISSUE THREAD

**Issue by Imveryweird** [richardfrost/AdvancedProfanityFilter#263]
![Screenshot_20201111-131630_Firefox.jpg](https://user-images.githubusercontent.com/66542108/98854450-30ba4800-2420-11eb-9dc1-e19067a7f2a8.jpg)

**Comment by richardfrost** [comment]
Interesting.. I just tried and it came right up for me. What device are you trying to access it with?

**Comment by Imveryweird** [comment]
Samsung S8+ on the latest firefox.

**Comment by richardfrost** [comment]
Interesting. I can't seem to find any errors in the log, and it is working for me on my Pixel 3 in Firefox. Can you try going to it again, and then let me know when you did it so I can double-check the logs (since I'm using the free version of Heroku it limits the amount of stored logs).

Also, if you had a chance to try with a different browser, I'd be interested to know if it works in another browser or not.

**Comment by Imveryweird** [comment]
It worked with another browser

**Comment by richardfrost** [comment]
Interesting... Well, I'm glad you were able to find a way for it to work. Can you share the version of Firefox that it wasn't/doesn't work with?
