### ISSUE TITLE
Hidden subtitles show/flicker for fraction of a second before hiding

### ISSUE THREAD

**Issue by PetrusV83** [richardfrost/AdvancedProfanityFilter#268]
Bug: Hidden subtitles show/flicker for fraction of a second before hiding

Browser: Firefox 84.0 (64bit)
OS: Win10
Site: www.primevideo.com (Amazon)

Description: This filter is awesome and thanks so much for all the hard work. I use it for various sites and it works great. However on Amazon (www.primevideo.com) when hiding subtitles they still appear for a fraction of a second (flicker on screen) before hiding. The other options like "Show only unfiltered" seem to work fine. I thought of using videoCueSync, but since Amazon uses Watcher mode for subtitles this won't work. Also thought of adjusting the checkInterval (even down to 1), but the glitch still appears. What is interesting is that it doesn't happen all the time. It happens periodically. Thought maybe it could be for the first sentence of a new scene or every ##th sentence. Not sure if this makes sense.

Thanks again.

**Comment by richardfrost** [comment]
Thanks, I'm glad you like it! Yeah, unfortunately that is due to the "watcher" method that is being used right now. I do have an idea or two to help minimize it, so I'll try to get to trying that soon. As you suspected, a lower `checkInterval` could possibly help, but its still not ideal, and it is still very likely to happen. I'll try out my experiments, and if they seem to go well, I'll post a beta build here for anyone interested in testing before it gets released.

**Comment by PetrusV83** [comment]
Awesome! Thanks Richard
