### ISSUE TITLE
Unable to add any new words to the filter

### ISSUE THREAD

**Issue by LtFrankDrebin** [richardfrost/AdvancedProfanityFilter#282]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :bug: Description
Hello. I've been experiencing a bug with this extension since November: I cannot add any new blocked words to Advanced Profanity Filter. If I try to add any, a pop up window appears with the following text: "The requested action failed. Please try again or contact support". My blocked list is really long, it contains hundreds of terms, I may have hit some kind of internal limit or something (this is only my speculation, however). 

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Try adding hundreds of words into your list.
2.  After a while, the aforementioned bug starts to occur (you'll be unable to add any words to the list).
3. See an error message.
4. If you try to add the same word again, it gets added to the list, but doesn't get blocked (so there may actually be two bugs instead of one).

#### :heavy_check_mark: Expected behavior
I want the extension to recognize new blocked terms that I add into it.

#### :camera: Screenshots
https://i.imgur.com/waKMfgd.png

#### :computer: Details
 - **Device:** PC
 - **OS:** Windows 10
 - **Browser:** Chrome
 - **Browser Version:** 88.0.4324.146 (Official Build) (64-bit)
 - **Affected site(s):** Any

**Comment by richardfrost** [comment]
Hi @LtFrankDrebin, thanks for reporting the issue. There is indeed a limit to the amount of storage space that can be used. Would you be willing to share your config, either by attaching it here, or sending it to me in an email? That way I can see specifically which limit is being hit, and see how to work around it. You can export it by going into the extension's Options page > Config tab > Export button.

**Comment by LtFrankDrebin** [comment]
Hello Richard,

Here's my config file:

[apf-backup-2021-02-09_065152.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/5948776/apf-backup-2021-02-09_065152.zip)

**Comment by richardfrost** [comment]
Thanks for sharing. So yes, you are correct on your suspicion. I have had a few users run into hitting the max size for words before, and I made an adjustment to spread those words out behind the scenes to help alleviate that, but it looks like your config has hit the max amount of storage that can be used by an extension in Chrome (and likely other browsers).

I can think of a few things that could help alleviate the issue:

1. Make the word config less verbose.
  a. Right now there is a lot of wasted space for each word. Every word also stores keys such as: `lists`, `matchMethod`, `repeat`, `separators`, and `sub`.
  b. We could optimize these by shorting the names (ex. `lists` -> `l`)
  c. We could also optimize storage by replacing true/false with 1/0
2. Add an option to choose where to store config.
  a. Add an option to store the extension's config in local storage because it will allow for much larger datasets.

A rough estimate looks like we could reduce the storage usage by about 23% by implementing option 1.

| Optimization      | Characters | %     |
|-------------------|------------|-------|
| Shorten Key Names | 27,745     | 18.8% |
| true/false        | 6,278      | 4.2%  |
| Total             | 34,023     | 23%   |

This would help, but it would really just kick the can down the road (although that doesn't mean it isn't worth considering). It would result in the config being less user friendly (at least in the case of shorter key names).

Option 2 would increase the storage limit from [102,400 Bytes](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync) to [5,242,880 bytes](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync), which is over 50x more. The cons with using this solution are:
- Add an additional check to see where to look for the config
- It may make the most sense to always use local storage, and if the config meets the criteria, we could treat local as a manual cache and push to sync.

Based on this, I'm thinking it probably makes the most sense to pursue Option 2, and I'll see what I find out as I experiment with that. Unfortunately I don't have a timeline for this, but I'll update here when I make some progress.

**Comment by LtFrankDrebin** [comment]
Hello richardfrost, is there any update on your progress with this feature (local storage)?

**Comment by richardfrost** [comment]
@LtFrankDrebin Actually, yes! I've been working on a complete rewrite of the storage layer, and its getting pretty close to being complete finally!

Here is the merge request if you're interested in following along for when it gets merged: #369. I'm hoping to have it in the next release. At this point I'm just doing some pretty in-depth testing, and then I have some more error handling to add, and some UI elements to explain the process better.

When its done, you should be able to switch to use local storage in the config tab of the extension's option page.

**Comment by LtFrankDrebin** [comment]
Thank you, richardfrost! That's great news! I'm looking forward to this update.

**Comment by richardfrost** [comment]
@LtFrankDrebin Just submitted version [2.30.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.30.0) to the various browser stores. When you get it, you should be able to switch the word/domain storage over to local storage by going to the Option's page > Config tab > and uncheck "Sync large settings".

If you try to import settings that are too large, or add words through the bulk word editor that are too large, it will prompt you with the option to switch to local storage as well.

Let me know how it goes for you! I did my best to thoroughly test it, but it was a huge change and its possible I missed something.

**Comment by LtFrankDrebin** [comment]
@richardfrost Everything works as intended, thanks a lot for this update. I've finally managed to enter new words into my filtering list for the first time since 2020. 

Could you tell me, please, in which folder the new local settings are stored so that I'll be able to back them up if I need to reinstall the system?

**Comment by richardfrost** [comment]
@LtFrankDrebin Sorry it took so long go get this addressed, but I'm glad to hear its working for you!

Everything is still being stored inside the browser (not in a separate file), but you can still use Option page > Config tab > Export to save a backup of your config. That will include all of your settings, including all the words you have added. With how much work you've put into your configuration, I definitely recommend saving a backup, and if you regularly make changes, probably make them monthly or whatever works best for you.

**Comment by LtFrankDrebin** [comment]
No worries. I just thought that when I unchecked "Sync large settings" in the "Config" tab, it meant that the settings are no longer stored in the cloud. I'll close this topic as you have successfully resolved the storage issue. Thank you!

**Comment by richardfrost** [comment]
@LtFrankDrebin It was a great question! Just to make sure its clear. The browser offers 2 different types of storage for extensions:

- Local storage: Saved locally on the device (still in the browser). This is not backed up to the cloud, but can store a lot more data
- Sync storage: Saved in the cloud and syncs between devices, but has much stricter limits on how much can be stored

Even if you only use Sync storage I'd recommend making backups, but its even more important when you are using local storage. I would also recommend storing those backups off the device (in dropbox, google drive, email, flash drive, etc.).
