### ISSUE TITLE
Wordlist filtered but audio not muted

### ISSUE THREAD

**Issue by reynekeadriaan** [richardfrost/AdvancedProfanityFilter#290]
Wordlist is filtered but audio is not muted nor is text censored in some movies in the Google Play Store. Settings have been checked and are correct and working for some of the movies.

**Comment by richardfrost** [comment]
Thanks for reporting the issue @reynekeadriaan. When I added Google Play Movies I only tested it on a handful of movies, so that doesn't really surprise me. Could you share a list of the movies that you've found where the filter doesn't work?

If I had to guess based on the information you shared, you may also want to give this custom audio config a go:

Options page > Audio tab > Custom Sites (right side, don't forget to click the "Save" button)

```json
{
  "play.google.com": [
    {
      "className": "lava-timed-text-window",
      "mode": "element",
      "subtitleSelector": "span.lava-timed-text-caption",
      "tagName": "DIV"
    },
    {
      "mode": "cue",
      "videoCueRequireShowing": false
    }
  ]
}
```

If you get a chance to try that, let me know if the filter behaves any differently. And if you can get me a list of movies that don't work I would be happy to see what I can find.

**Comment by reynekeadriaan** [comment]
Hi there

Thanks for getting back to me. I have tried the changes in the Audio tab
but it only still filters the words but does not mute the audio.

I currently do not have a list of movies as we have only recently
discovered your filter and are now browsing through all the movies that
what we have missed out on so far.

One we have a issue with now is - Live Die Repeat: Edge of Tomorrow on
Google Play.

Thanks
Adriaan

**Comment by richardfrost** [comment]
Okay, I don't have that video in my library right now, and I'm not sure I'll have time to work on it with just a rental right now. I will try to take a look at it soon though. If you come across another one that doesn't work, please let know.

In the mean time, another thing you can try is to watch the movie on YouTube. As far as I know, once you have it on Google Play you should be able to watch it on YouTube as well, and those captions should work as they are more consistent.

One final option might be to setup a Movies Anywhere account, which should let you watch movies on different platforms such as Vudu or Amazon.
