### ISSUE TITLE
HBOMax

### ISSUE THREAD

**Issue by acougle** [richardfrost/AdvancedProfanityFilter#293]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :twisted_rightwards_arrows: Steps To Reproduce
Having problems again with Advanced Profanity Filter and HBO Max.
Ex. https://play.hbomax.com/episode/urn:hbo:episode:GX0aOrArD0hTCwwEAAANO
AND specific example at 7:20
I've turned filter off and on several times and filter is not working. And, play.hbomax.com is enabled as a domain.
Is there a specific script or something that I need to enter to enable?
Thanks

#### :computer: Details
 - **Device:** [SurfaceBook Pro]
 - **OS:** [Windows 10]
 - **Browser:** [Chrome]
 - **Browser Version:** [Version 89.0.4389.128]
 - **Affected site(s):** [play.hbomax.com]

**Comment by richardfrost** [comment]
Thanks for reporting the issue, but I'm sorry it isn't working for you. I just tested with the timestamp you shared, and it seemed to successfully mute for me. Could you check and make sure you don't have any custom site config set for `www.hbomax.com` (Options page > Audio tab > Custom Sites box)?

HBO Max has an interesting way they handle the presentation with their captions/subtitles, which could be leading to the issue. If the step above wasn't the issue, could you try opening the Caption settings in HBO Max and click the "Reset" button? I have seen that fix the issue a few times. If there is a specific setting for the captions that you would like, share it with me and I can give  you a custom config that will work with it. Unfortunately due to the way it is setup, the filter right now only supports the default caption settings. If changes are made, the filter no longer correctly identifies the captions/subtitles.

**Comment by richardfrost** [comment]
I apologize for that. I was just glancing at the config fast and misread the play.hbomax.com. You are correct it should be the play one. One thing I do when testing is temporarily add a non-vulgar word to the filter,  and test with that. You may find that useful so you don't keep having to hear an undesired word until we get it solved. I have a few more questions that come to mind:

-  Are the captions showing when you are trying to mute?
- Would you mind sharing a copy of your configuration file? If not, that's okay. I would also encourage maybe trying to export the config as a backup, and then try restoring the defaults. Then go turn on audio muting again, and see if it works. If so, then we know it's something in the config (not necessarily that you did anything wrong with it, but you may have found a bug).

- Finally another thing that might help is to pause the video while some captions are showing, and then inspect the element. This is a little more technical, but shouldn't be too bad:
  1. While the video is paused and captions are showing, right-click (or bring up the context menu) over the caption text and choose "Inspect element" (Or possibly just "Inspect").
  2. Press Control-F (on PC) and type in a word or two from the captions that are visible. It should highlight them in the "Elements" tab. Take a screenshot of the screen and attach it. I'll attach a picture of what mine looks like.
  
  
![image](https://user-images.githubusercontent.com/1507205/115301853-febfb700-a11e-11eb-96eb-ff6f90747aa2.png)

**Comment by richardfrost** [comment]
After lots of reports and observation, I have made a new beta version that completely overhauls the muting code for HBO Max. Please give it a try and let me know if it works okay for you, and if other sites are still working. Thanks.

[APF-hbomax-beta.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/6463365/APF-hbomax-beta.zip)

[How to use](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension)

**IMPORTANT**: If you import your settings to this beta build, please make sure to remove/modify any custom audio site rules you have for `play.hbomax.com` before testing this.

**Comment by richardfrost** [comment]
Version [2.19.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.19.0) changed the method that HBO Max is using. This new mode was designed to handle different subtitle options (where before it needed to be the default, or every once in a while the subtitle settings for HBO Max had to be reset). I had a few people test it with success, but if you try it out, please let me know how it works for you. Thanks!
