### ISSUE TITLE
Phrase won't censor on TvTropes.

### ISSUE THREAD

**Issue by RiffyDiffy** [richardfrost/AdvancedProfanityFilter#296]
#### :bug: Description
While I was browsing through the Friday Night Funkin page on TvTropes, I added the phrase "God... F'ing...." in the extension, but when I came back...
Yeah, it won't censor at all, for some strange reasons.
#### :twisted_rightwards_arrows: Steps To Reproduce
Add this phrase "God... F'ing...." to the extension and there you go.

#### :heavy_check_mark: Expected behavior
Well, to be censored, of course.

#### :camera: Screenshots
https://i.ibb.co/W6dSGgt/censorproblem.png Here's proof.

#### :computer: Details
 - **Computer: HP Pavilion Computer:**
 - **OS: Windows 10 Home Insider Dev Build 21359:**
 - **Browser: Microsoft Edge:** 
 - **Browser Version Version 90.0.818.39 (Official Build)** 
 - **Affected site(s): https://tvtropes.org/pmwiki/pmwiki.php/VideoGame/FridayNightFunkin**

**Comment by richardfrost** [comment]
It looks like you may have added one too many `.` after the last word of your phrase. When I remove that it looks like it worked as expected.

In your example you have selected to "match repeated characters", which means you could even simplify it because that feature will match 1, or any other number immediately following of that same character. So, you could add this to your filter: `god. f'ing.` and it will match `god... F'ing...` or `god. F'ing.............................`. Let me know if that fixes it for you, or if you have any other questions.

**Comment by RiffyDiffy** [comment]
> It looks like you may have added one too many `.` after the last word of your phrase. When I remove that it looks like it worked as expected.
> 
> In your example you have selected to "match repeated characters", which means you could even simplify it because that feature will match 1, or any other number immediately following of that same character. So, you could add this to your filter: `god. f'ing.` and it will match `F'ing...` or `god. F'ing.............................`. Let me know if that fixes it for you, or if you have any other questions.

Works for me now, thanks!
