### ISSUE TITLE
Subtitles are censored but not audio for YesMovies

### ISSUE THREAD

**Issue by ANIM8RX** [richardfrost/AdvancedProfanityFilter#298]
I tried following the guide but the console was not detecting the subtitles on this website: www4.yesmovies.so

I have the plugin running on the website and it censors text in the subtitles, but the audio does not get muted. Is there any way to get this to work on this specific website? 

Any help would be appreciated!

**Comment by richardfrost** [comment]
Sites like these can be difficult because they end up streaming from many different servers, and can each supply their own video player that may not use the same rules as another. That being said, I tested on a few different movies with this config:

```json
{
  "www4.yesmovies.so": [
    {
      "className": "jw-text-track-container",
      "iframe": true,
      "mode": "element",
      "subtitleSelector": "div.jw-text-track-cue",
      "tagName": "DIV"
    }
  ]
}
```

Give that a try and let me know how it goes. If you have a specific movie/server that it doesn't work on let me know and I'll take another look at it.

**Comment by ANIM8RX** [comment]
Hi Richard, it seems to be working now after I put in the necessary code that you sent. Thank you so much!

**Comment by richardfrost** [comment]
Glad to hear it. Enjoy! As this isn't a "mainstream" streaming site, I won't be adding it to filter directly, but I have recorded it along with other configs [here](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Audio-Muting:-Additional-Sites).
