### ISSUE TITLE
TierMaker won't censor words.

### ISSUE THREAD

**Issue by RiffyDiffy** [richardfrost/AdvancedProfanityFilter#340]
#### :bug: Description
A similar event happened to me, but that was a long time ago, now I wanted to point out that the website TierMaker doesn't actually censor words.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to any tier.
2. Enter any ugly word in one of the labels.
3. And there you have it.

#### :heavy_check_mark: Expected behavior
I wanted it to be censored, but simply, it wouldn't.

#### :camera: Screenshots
Here's the screenshot: https://i.ibb.co/ctkLLS3/2021-09-26-18-59-56.png (Ignore the fact that I added the word "Stupid" into the wordlist.)
I swear the extension was on.

#### :computer: Details
 - **Computer:** HP Pavilion Computer
 - **OS:** Windows 11 Insider Beta Version 22000.194
 - **Browser:** Vivaldi
 - **Browser Version:** 4.2.2406.48 
 - **Affected site(s):** https://tiermaker.com/create/cookie-run-kingdom-characters-august-2021-340541

#### :pencil: Additional context
Nothing, that's it.

**Comment by richardfrost** [comment]
This is actually happening by design. The filter doesn't filter editable fields, because it can cause issues with emails, spreadsheets, etc. Basically the reasoning is if it's a content-editable field, it was likely typed by the person using the filter, and therefore they don't want it filtered. As of right now there isn't really a workaround. You can use the web developer tools and remove `contenteditable="true"` from the element and then update the text manually to trigger the filter to process it, or you could copy a phrase into the Options page > Test tab to get the filtered results out, and then copy that to the list. Like I said... not really a good workaround.

Is there a way to get a read-only version of the list/page? If so, that might be a solution for the filter. 

If you can't find one... I guess we could add a domain-specific setting to allow filtering of editable content which could address this.

**Comment by richardfrost** [comment]
Due to inactivity, I'm going to close this. If this is still an issue, feel free to respond and re-open this issue.
