### ISSUE TITLE
Muting embedded youtube videos

### ISSUE THREAD

**Issue by BE-Code** [richardfrost/AdvancedProfanityFilter#343]
Just out of curiosity, does the extension already handle YouTube videos embedded in other sites? I'm trying to sift through all the code to understand how it all works together, and I came across [webAudioSites.ts](https://github.com/richardfrost/AdvancedProfanityFilter/blob/master/src/script/webAudioSites.ts). It has a list of sites with custom configurations for where to find the captions on the page, I assume. So for other random sites that may have a YouTube video on the page, will it be picked up or do we need a configuration for those sites too? (references of files are helpful so I can understand this better)

**Comment by richardfrost** [comment]
If you check out #242 you'll see some more discussion on this topic. Basically right now, the filter should support embedded YouTube videos that are embedded as an `IFRAME`. That seemed to work on all sites I tested with, but if you see some that don't work let me know.

You are correct that the webAudioSites.ts file includes all the supported audio muting sites and accompanying rules for muting (and identifying captions on the page). YouTube specifically is interesting, because the support for Auto-generated subtitles is currently not using the same framework as the other sites, but is built into the `WebAudio` class [webAudio.ts](https://github.com/richardfrost/AdvancedProfanityFilter/blob/master/src/script/webAudio.ts), and a few other places (basically search for `youtube` throughout the project). I do have a branch I'm working on to update those autoSubs functions to fall into place, but it has taken a back seat for now.

As an overview, the audio logic only runs when there is a matching set of rules (as defined in webAudioSites.ts) for the current site. That is done in an effort to not waste resources because the audio muting does add some overhead, and if we don't have rules to check it against then there isn't a point to running it. If there is a matching rule, then we turn on the audio muting functionality for the page, and when there are changes (mutations) to the site we process them checking to see if they are captions/subtitles.

Let me know if you have any other questions!

**Comment by richardfrost** [comment]
Due to inactivity, I'm going to close this. If this is still an issue, feel free to respond and re-open this issue.
