### ISSUE TITLE
Fails to substitute on opera since last update.

### ISSUE THREAD

**Issue by ballsystemlord** [richardfrost/AdvancedProfanityFilter#354]
#### :bug: Description
APF fails to substitute f**k on opera. This occurs on regular webpages as well as the "test" page in APF's settings.
It still works on Firefox with identical settings.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Install APF into opera.
2. Go to APF test page. 
3. Type in f**k to substitute.
4. See original word in the substitute box.

#### :heavy_check_mark: Expected behavior
I expect APF to substitute the f**k to junk.

#### :computer: Details
 - **Device:** PC Ryzen 3900X.
 - **OS:** Devuan (Debian) Linux.
 - **Browser:** opera
 - **Browser Version:** 80.0.4170.72
 - **Affected site(s):** It seems to not work everywhere.

#### :pencil: Additional context
Here's my config for reproduction purposes.
[apf-backup-2021-11-08_072405.txt](https://github.com/richardfrost/AdvancedProfanityFilter/files/7496985/apf-backup-2021-11-08_072405.txt)

Thanks!

**Comment by richardfrost** [comment]
Thanks for reporting the issue, and sharing so many details. Hopefully we can get it resolved quickly! First off, are you using APF from the [Opera Store](https://addons.opera.com/en/extensions/details/advanced-profanity-filter/), or the [Chrome Store](https://chrome.google.com/webstore/detail/advanced-profanity-filter/piajkpdbaniagacofgklljacgjhefjeh/related?hl=en). While they are both compatible with Opera, the official Opera version is several versions behind because the newer releases are stuck in their review process. Not sure why I can't get an update out, but its been that way for well over a year at this point.

I definitely recommend using the Chrome version in Opera at least until the update issue can get resolved. If you are already using the Chrome version, or that doesn't solve the issue, could you give an example of a site that is having the issue? It seemed to work for me with your settings on the sites I tested.

**Comment by ballsystemlord** [comment]
Thanks for getting back to me so quickly. The updated chrome store addon fixes the problem!

**Comment by richardfrost** [comment]
Awesome! I'm glad its working for you now. I hope they can resolve the updates I've submitted over at Opera soon.
