### ISSUE TITLE
Toggle Switch Broken

### ISSUE THREAD

**Issue by Ferrous27** [richardfrost/AdvancedProfanityFilter#370]
#### :bug: Description
After the 26 January update, the easy toggle switch for the plugin that comes up when the icon is clicked is no longer functional, even after refreshing the page.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Click on the extension icon in the toolbar
2. Click on the button next to the logo
3. Webpage will not update.

#### :heavy_check_mark: Expected behavior
It should update the webpage like before the 26 Jan update.

#### :computer: Details
 - **Device:** PC Laptop
 - **OS:** W10
 - **Browser:** Firefox 
 - **Browser Version:** 96.0.3 (64-bit)
 - **Affected site(s):** All

**Comment by richardfrost** [comment]
Interesting, I just checked it and it seems to work with the default settings in Firefox 96.0.3 for me. Could you try one of these?

- Send me a copy of your config (Options page > Config tab > Export)
- Save a backup of your config, restore the defaults and try again?

Because there are so many variations of settings, sometimes its hard to track down which one might have introduced the issue.

**Comment by richardfrost** [comment]
@Ferrous27 Just wanted to follow up with you. Are you still having this issue?

**Comment by richardfrost** [comment]
I'm going to close this, but feel free to re-open and respond if you are still having this issue.
