### ISSUE TITLE
Chrunchyroll/Funimation Subtitles 

### ISSUE THREAD

**Issue by Commonman7** [richardfrost/AdvancedProfanityFilter#378]
Does not appear to be filtering subtitles on Crunchyroll or Funimation

**Comment by richardfrost** [comment]
It looks like this was likely caused by switching to Manifest V3 on Chromium-based browsers. I've reverted back and it seems to be working again. Once you get upgraded to version [2.32.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.32.1), let me know if it starts working again for you.

In the meantime, you can use Firefox if you want as it should be working, though Chrome is usually pretty quick about updates. If you installed from the Microsoft Edge store it may take 3-5 days for the update to be available.

**Comment by Commonman7** [comment]
I finally got a chance to try it out. Is seems to be working fine now.
Thanks for your help.

**Comment by richardfrost** [comment]
You're welcome! Thanks for reporting the issue!
