### ISSUE TITLE
Error in console since new update

### ISSUE THREAD

**Issue by Fabian9799** [richardfrost/AdvancedProfanityFilter#393]
#### :bug: Description
Since the new update the extensions shows ``Uncaught (in promise) Error: The message port closed before a response was received.`` in the console of every website

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to a random website
2. press F12 (or open the console somehow)
3. See error

#### :heavy_check_mark: Expected behavior
The error should not show up

#### :camera: Screenshots
![image](https://user-images.githubusercontent.com/19490891/158809634-824752b5-b40f-4a23-b580-5bc5679cb69e.png)

#### :computer: Details
 - **OS:**Windows 11 Pro 22000.527
 - **Browser:** Brave
 - **Browser Version:** Brave Version 1.36.112, Chromium: 99.0.4844.51
 - **Affected site(s):** all websites where the extension has access

**Comment by richardfrost** [comment]
Thanks for reporting the issue.

Turns out its actually a change to `sendMessage` in Chrome 99.

- [Bug 1304272](https://bugs.chromium.org/p/chromium/issues/detail?id=1304272)
- [Stack Overflow Explanation](https://stackoverflow.com/questions/71520198/chrome-extension-manifest-v3-unexpected-promise-errors)

Aside from the console noise, this shouldn't cause any issues. I'll get a patch out to address it soon though.

**Comment by richardfrost** [comment]
This should be fixed in version [2.33.4](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.33.4). I'm going to go ahead and close it, but feel free to reply here once you've had a chance to test it. I'm happy to re-open the issue if this didn't fix it.

**Comment by Fabian9799** [comment]
The error message is gone now. Thanks for the fix.

**Comment by richardfrost** [comment]
@Fabian9799 glad to do it! Thanks for reporting its resolved.
