### ISSUE TITLE
Doesn't work with dashes

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#395]
I've tried adding B-*-*-*-* to my block list, but it won't work. I think it has something to do with the dashes in between the letters.

**Comment by richardfrost** [comment]
Not sure on all your settings for the word, but if I try to add it with the defaults I am not able to get it to filter either. I'm going to assume you are using the "Exact" Match Method. When I use partial it works. Its failing with "Exact" because it produces the regex: `/\bb----\b/gi`, which is causing issues with word boundary detection.

For now you can probably get by with the "Partial" Match method, but I'll take a look later and see if I can work around it for the "Exact" match method.

**Comment by richardfrost** [comment]
This should be fixed in version [2.33.4](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.33.4). I'm going to go ahead and close it, but feel free to reply here once you've had a chance to test it. I'm happy to re-open the issue if this didn't fix it. Thanks again for reporting the issue.
