### ISSUE TITLE
Netflix app

### ISSUE THREAD

**Issue by Hanhtkpham** [richardfrost/AdvancedProfanityFilter#438]
Hello,   I wanted to use this on my iPhone but Netflix only let you play video on their app.      Is there a way I can use this filter on Netflix or how does it work exactly.  Only on my monitor?   Can I download the same filter account to the monitor then?   Thank you.

**Comment by richardfrost** [comment]
Hi @Hanhtkpham, thanks for reaching out! Unfortunately since this is just a browser (Safari) extension, it can only work there. Every streaming platform is a little different, and there are some that don't allow playback on a mobile device in a browser, but require you to use their app. To complicate it further, those requirements vary depending on the country you access from as well. If you can't watch a video in Safari from the desired site, this filter probably won't be able to work for audio muting.

If you have a laptop or desktop, it should work there.

**Comment by richardfrost** [comment]
@Hanhtkpham, I'm going to close this issue, but feel free to respond or re-open if you have any other related questions.
