### ISSUE TITLE
Help with blocking audio with jw-text-track-cue

### ISSUE THREAD

**Issue by Sliicy** [richardfrost/AdvancedProfanityFilter#472]
Hello! Your extension is amazing! It is blocking curse words on the following site, but not audio. I tried following the instructions to add audio, but got lost. How can we add audio blocking to this site?

#### :movie_camera: The Site
losmovies.ru

#### :speech_balloon: Subtitle Element/Node
```html
<div class="jw-text-track-display jw-reset">
<div class="jw-text-track-cue jw-reset">These are where the captions appear.</div>
</div>
```
(I trimmed out the styling from above HTML for brevity.)

Your help is greatly appreciated!

**Comment by richardfrost** [comment]
Thanks for giving it a try! Sorry its not a very friendly process yet. Also, this site is definitely more difficult than most. Because this site's legitimacy isn't confirmed, I won't be adding it as a supported site. I do think I have a [working config](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Audio-Muting:-Additional-Sites#site-losmoviesru) for it though, and you are welcome to add it to your "Custom Sites Config".

If you decide to use, let me know how it works for you!

**Comment by Sliicy** [comment]
Thank you!
