### ISSUE TITLE
Advanced Profanity Filter 1.0.2 default words!!

### ISSUE THREAD

**Issue by on1no** [richardfrost/AdvancedProfanityFilter#56]
## Description
Please See the Youtube Video Link it will explain everything
https://youtu.be/Lcf9UcZqEVk

### Details (Bugs Only)

Chrome Version: 63.0.3239.132
Extension Version: 1.0.2
Operating System: Win 10
Site(s) Affected:

**Comment by richardfrost** [comment]
Thank you for the video, that illustrated the problem very well.

There definitely was a problem with it before, so thank you for making me look at it. I do believe it has been fixed though. Here is the new expected behavior:

If there are no words (Ex: You delete them all and don't add any new ones) it will use the defaults. The filter without any words is useless, so that's why I chose to use the defaults. If you retry your test and remove just one word, that word won't be filtered. Also, if you add a new word, like `testing` you can remove all other words and `testing` should be the only word in the list. You can then add whatever else you want to. Just remember, if you remove all words, it will re-populate the defaults.

I hope that makes sense, and that it is an acceptable answer.

**Comment by on1no** [comment]
![tenor](https://user-images.githubusercontent.com/35997957/35640371-05c7a786-06ce-11e8-8948-68b7c04435e8.gif)
you are absolutely right 

i Just add a New Word and Remove The defaults list And its Working Perfect 👍 

![tenor 1](https://user-images.githubusercontent.com/35997957/35640362-0207dbc0-06ce-11e8-9099-6e5bd35c6cdc.gif)
Problem solved

Thank you Sir.

**Comment by richardfrost** [comment]
You are very welcome! Thanks for taking the time to reach out for support, glad we could get it working!
