### ISSUE TITLE
Filter only applied after page loaded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [richardfrost/AdvancedProfanityFilter#7]
```
Issue submitted by Martin on Chrome Extension Gallery page:
Hi Mark, the problem with this extension is that it loads the page and only 
then replaces the words. There is a "beforeload" event out now which you can 
use to prevent these bad words from loading at all. I STRONGLY suggest that you 
use it. AdBlock is using it too. It's much better if you don't even load the 
bad word rather than load it and then hide it...


```

Original issue reported on code.google.com by `markyd13` on 2 Aug 2010 at 8:08

**Comment by richardfrost** [comment]
Because the extension uses XPath right now to process each node, I don't think that this is the right way to handle this. Here is an example of the beforeload event though.

https://stackoverflow.com/questions/11386246/addeventlistenerbeforeload-missing-events

document.addEventListener( 'beforeload', function( event ) {
    event.preventDefault();
}, true );

Occasionally I do get a page that loads slower and I can catch a glimpse of unfiltered words, but it seems to be quite brief to me. I will wait to hear more feedback on this.
