### ISSUE TITLE
Not working completly on this site.

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#76]
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

### Details (Bugs Only)

Chrome Version:Yes and Firefox
Extension Version:1.0.1.1
Operating System:Windows 10 Home
Site(s) Affected:http://www.commercialsihate.com/the-eliquis-archaeologist-moron_topic20696.html

### Steps to reproduce (Bugs only)

1.The F word is not being filtered on this page.

**Comment by tonyram57** [comment]
Weird how it censored other profanities on that page except for that one.  Even adding the first three letters did not work which made me think it was masked some how.

Thanks for your extension I find profanity on webpages at a few times a hour mainly from doing Google searches for anything.  I will never bother reading webpages anymore if not for this extension.

**Comment by richardfrost** [comment]
Yeah, if you take a look at the right side of that screenshot above you can see the WHY it doesn't work, but its unfortunate.

```html
... those big fu"
<i>c</i>
"king yucky..."
```

Like you said, the extension is working on the page, but under the hood it only works inside HTML tags, and since there is a `<i>c</i>`, the extension ends up seeing the following groups of text:

1.  `...those big fu`
2.  `c`
3. `king yucky...`

So, if you were to add the first 2 letters that would work (well, filter the first 2 letters), because its in the first group together. But adding the first 3 letters won't work because its in a different group (`c` is in the second group by itself), and the extension only looks at one group at a time. Unfortunately this looks like a case where the poster tried to hide the word, which is quite effective. The reason the extension doesn't act on HTML tags, and only works in groups is due to performance and compatibility. I don't think there is a good way to adapt to this problem without making a sacrifice that I don't think would be worth it right now.

I'm glad that you are finding the extension helpful in other instances, and hope that it will continue to make your time browsing the web more enjoyable. If you have any other feedback, suggestions, or questions, let me know!

**Comment by tonyram57** [comment]
Considering that forum like many others is completely uncensored it made no sense to even try to get around the profanity.  Unless it is a glitch in the site as some boards will actually convert your text you type into HTML code and I had some posts glitch with code and my text mixed in.

**Comment by richardfrost** [comment]
I feel like it's a bit too granular to have different words for different sites. In this one instance, you COULD add the word: "fu" and set its matching method to `Exact`. That would not cause false positives (ie it wouldn't match "fun"), but would still do some filtering.

I will note your request, and if it gets more attention I may implement it, but for right now it would take a lot of work, and I don't see it as being something that most users would use.
