### ISSUE TITLE
Problems with new Faster Initial Filtering

### ISSUE THREAD

**Issue by Mohfath** [richardfrost/AdvancedProfanityFilter#84]
Thanks for the great project.

I would suggest making the "Faster Initial Filtering" feature, as an option.
Since the site I am using, worked fine with last version but by moving to this new Version, all the words are plainly visible and number of filtered words are always zero.

I presume it is a matter of texts loading with javascript waaay after your extension's run.

**Comment by richardfrost** [comment]
Thanks for letting me know, and I'm glad you like the project.

I was afraid that something like this would happen, and unfortunately it is not possible to make the change an option. My testers had trouble with Reddit which we were able to work around, would you mind sharing which site has the issue? Ultimately I may have to revert that change all together.

**Comment by tonyram57** [comment]
> Ultimately I may have to revert that change all together.
Please don't.  I am finding the script more reliable than it was before.  What Richardfrost said what site is giving you issues.  Sure it is not static images made to look like text as no add on can block profanities in images.

**Comment by richardfrost** [comment]
I will definitely try to solve the problem through other means, as I think the faster initial filtering offers a lot of benefits. I am pretty confident I can work around the issue, so @Mohfath, please let me know what site is causing the problem so I can take a look.

**Comment by richardfrost** [comment]
I am working on a new "comprehensive" setting, which can be turned on for specific domains. It will allow the filter to be more aggressive/thorough than normal, and will be able to potentially block more words. It will be opt-in for a domain though, because it can also cause more slowdowns and potentially even break a page. Hopefully it will be useful for particularly difficult pages, but not enabled elsewhere.

**Comment by richardfrost** [comment]
@Mohfath I have published the "Advanced Mode", which can be enabled on a per-domain basis (Options -> Domains- > Advanced). The new version has other improvements as well, so please let me know if you are still having issues with a particular site. Otherwise in a few days I'll go ahead and close this.

**Comment by richardfrost** [comment]
Since there hasn't been any activity on this I'm going to close it. If its still an issue, please try the advanced domain option, and let me know how that goes.
