### ISSUE TITLE
Not working with search bar on Play Music.

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#86]
Just notice when searching on Play Music it does not filter the search terms (used minor swear word) as pictured below.
![2018-07-13_153136](https://user-images.githubusercontent.com/39742654/42710483-37d8059a-86b2-11e8-865f-757bdc9cbefc.png)

However the script is working when viewing the results.
![2018-07-13_153153](https://user-images.githubusercontent.com/39742654/42710502-49ba55b0-86b2-11e8-8887-840f1cc6620d.png)

**Comment by richardfrost** [comment]
Interesting - do you know if it was working before? I will try to test an older version tonight, but I don't know if I have ever tested that before. I just want to know if it was a recent change, or if it has never worked.

**Comment by tonyram57** [comment]
I tried Firefox and Chrome both the same.  I don't know when it started just noticed when searching I saw some worse profanities which is why I posted the minor profanities here to demonstrate.  Also I do use a stock script.  I don't add any words I also leave the app with its defaults so it filters profanities that are spelled with other words so it looks like ****you will filter and not just ****.

**Comment by tonyram57** [comment]
Also forgot to say but it is working only 
![2018-07-13_164040](https://user-images.githubusercontent.com/39742654/42712940-93aa9a78-86bb-11e8-864e-559af3a5766c.png)
if I don't search and click on my Play music search history.

**Comment by richardfrost** [comment]
Awesome, thanks for all the details! That will definitely help when tracking down what is going wrong.

**Comment by tonyram57** [comment]
Thanks and yes it did do it with the last few previous version so it is not the FastFilter causing it if anything the FastFilter is blocking more profanities.

**Comment by richardfrost** [comment]
> yes it did do it with the last few previous version so it is not the Faster Internal Filter causing it

Do you mean that it **wasn't** filtering the Google Play Music search results for the last few versions?

I'm glad that you are enjoying the new faster filtering. I agree that I have found it to be working better as well.

**Comment by tonyram57** [comment]
> Do you mean that it wasn't filtering the Google Play Music search box for the last few versions?
Not really sure as I only started to use Play Music for a couple of months when unrelated story Apple Music took off some albums that Play Music still has.

**Comment by richardfrost** [comment]
Alright - I have a new version that I'm playing around with. It seems to work for me on Google Play Music better, and I think its also a much cleaner way to handle the new Reddit redesign too (It does result in 2x on the count, but that's because it actually does filter all words a second time). I only had time to package the chrome build for testing ([extension-chrome.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/2198843/extension-chrome.zip)), but I can try to get a Firefox one tonight.

Feel free to try it if you get some time. I'd love some more feedback, and I'd love to make sure it doesn't break things elsewhere. Also - let me know if you notice any degradation in performance. I think it should be pretty solid, but I am always looking for more support/feedback.

**Comment by richardfrost** [comment]
The latest release has been published for both Chrome and Firefox. Please let me know if you have any comments about the release, otherwise I'll close this in a few days.

**Comment by tonyram57** [comment]
Okay it is working better but it still does not filter the last two history titles.
![2018-07-20_131626](https://user-images.githubusercontent.com/39742654/43015969-35dfd052-8c1f-11e8-8a2b-1e75cbcc88e0.png)

**Comment by richardfrost** [comment]
Yeah, I probably should have mentioned that. So the only way that is really feasibly is to use the Advanced mode for `play.google.com` (Options -> Domain -> Advanced). Please note, that the advanced mode is potentially destructive (ie can prevent the page from working). I haven't had trouble with it on Google Play Music thus far, but no guarantees. The advanced mode will filter previous searches, and search words when they are all typed out in full, or not at all. Explanation on that below.

Notice in your screenshot that "claremont shades" is a lighter grey, and then the darked color is present in what you actually typed in the search bar. Well, when you are typing, for instance the word "wish", as you type each letter, it will change the color darker. Under the hood they are actually split up into different elements, and therefore are not part of the same word. So, if you were to add the word "wish" to the filter, and then search for "wis", it would look something like "**wis**h". Behind the scenes, this translates to `<tag>wis</tag><tag>h</tag>`. This ultimately leads to the filter seeing 2 different words: "wis" and  "h", which of course doesn't match "wish", so nothing gets filtered.

Unfortunately there isn't a good, repeatable way to address this, because on almost every other webpage they don't follow this practice. On the plus side, this DOES work for suggestions that might contain a filtered word, as long as you aren't searching directly for the word. For instance, try searching "wish i was" and it should be filtered.

**Comment by tonyram57** [comment]
Thanks.  As I said I purposely searched for "damn" because it is a lesser profane word to brute force test the extension.  Otherwise I won't be purposely searching for profane title songs just artists.

**Comment by richardfrost** [comment]
Yep, I ended up doing the same in my testing. For the future, you may try adding a completely harmless word, like `book` or something to the filter temporarily. Not necessary, but I've done that at times and had pretty good success from a testing perspective.

Also - if you are interested, I was able to clear the search from my history [here](https://myactivity.google.com/item?q=google%20play%20music&product=16). You should be able to target the specific search from there.

**Comment by tonyram57** [comment]
Thanks for the clear history link.  There is no way I will purposely search for profane title songs that song is minor.
